pipeline {
  agent any
  
  stages {
    stage('Clone Repository') {
      steps {
        git '<YOUR_REPOSITORY_URL>'
      }
    }
    
    stage('Build and Test') {
      steps {
        sh 'pip install -r requirements.txt'
        sh 'python manage.py test'
      }
    }
    
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t 448568155388.dkr.ecr.eu-west-2.amazonaws.com/django-k8s-app:latest .'
      }
    }
    
    stage('Push Docker Image') {
      steps {
        withCredentials([usernamePassword(credentialsId: '$DOCKER_REGISTRY_CREDENTIALS_ID', passwordVariable: '$DOCKER_PASSWORD', usernameVariable: '$DOCKER_USERNAME')]) {
          sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
          sh 'docker push 448568155388.dkr.ecr.eu-west-2.amazonaws.com/django-k8s-app:latest'
        }
      }
    }
  }
}
// https://448568155388.signin.aws.amazon.com/console